export const CARS_REQUEST = 'CARS_REQUEST'
export const CARS_SUCCESS = 'CARS_SUCCESS'
export const CARS_FAIL = 'CARS_FAIL'


export const CARS_CREATE_REQUEST = 'CARS_CREATE_REQUEST'
export const CARS_CREATE_SUCCESS = 'CARS_CREATE_SUCCESS'
export const CARS_CREATE_FAIL = 'CARS_CREATE_FAIL'
