export const CARS_REQUEST = 'CARS_REQUEST'
export const CARS_SUCCESS = 'CARS_SUCCESS'
export const CARS_FAIL = 'CARS_FAIL'


export const CARS_CREATE_REQUEST = 'CARS_CREATE_REQUEST'
export const CARS_CREATE_SUCCESS = 'CARS_CREATE_SUCCESS'
export const CARS_CREATE_FAIL = 'CARS_CREATE_FAIL'
export const CARS_CREATE_RESET = 'CARS_CREATE_RESET'


export const CARS_DELETE_REQUEST = 'CARS_DELETE_REQUEST'
export const CARS_DELETE_SUCCESS = 'CARS_DELETE_SUCCESS'
export const CARS_DELETE_FAIL = 'CARS_DELETE_FAIL'
export const CARS_DELETE_RESET = 'CARS_DELETE_RESET'


export const CARS_SELECTED = 'CARS_SELECTED'
export const CARS_UPDATE_REQUEST = 'CARS_UPDATE_REQUEST'
export const CARS_UPDATE_SUCCESS = 'CARS_UPDATE_SUCCESS'
export const CARS_UPDATE_FAIL = 'CARS_UPDATE_FAIL'
export const CARS_UPDATE_RESET = 'CARS_UPDATE_RESET'